[postgres_prod]
192.168.50.15

[postgres_stage]
192.168.50.16

[postgres_dev]
192.168.50.28

[postgres:children]
postgres_prod
postgres_stage
postgres_dev

[dns]
192.168.50.53

[nexus]
192.168.50.12

[step_ca]
192.168.50.9

[openclaw]
192.168.50.90

[docker]
192.168.50.91
192.168.50.92

[openwebui]
192.168.50.91

[hermes]
192.168.50.92

[k3s_prod_servers]
k3s-prod-server1 ansible_host=192.168.50.17
k3s-prod-server2 ansible_host=192.168.50.18
k3s-prod-server3 ansible_host=192.168.50.19

[k3s_prod_agents]
k3s-prod-node1 ansible_host=192.168.50.23
k3s-prod-node2 ansible_host=192.168.50.24
k3s-prod-node3 ansible_host=192.168.50.25
k3s-prod-node4 ansible_host=192.168.50.26
k3s-prod-node5 ansible_host=192.168.50.27

[k3s_stage_servers]
k3s-stage-server ansible_host=192.168.50.14

[k3s_stage_agents]
k3s-stage-node1 ansible_host=192.168.50.20
k3s-stage-node2 ansible_host=192.168.50.21
k3s-stage-node3 ansible_host=192.168.50.22

[k3s_dev_servers]
k3s-dev-server ansible_host=192.168.50.29

[k3s_prod:children]
k3s_prod_servers
k3s_prod_agents

[k3s_stage:children]
k3s_stage_servers
k3s_stage_agents

[k3s_dev:children]
k3s_dev_servers