---
- name: Provision step-ca skeleton on dedicated host(s)
  hosts: step_ca
  become: true
  vars:
    step_ca_install_method: manual
  vars_files:
    - "vars/common/vars.yaml"
    - "vars/common/secrets.yaml"
  roles:
    - step-ca