docker_primary_user: jason
docker_apt_arch_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf

docker_apt_arch: "{{ docker_apt_arch_map.get(ansible_architecture, ansible_architecture) }}"
docker_apt_repository_name: docker
docker_apt_repository_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
docker_apt_repository_key_url: "{{ docker_apt_repository_url }}/gpg"
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_compose_example_enabled: true
docker_compose_project_name: sample-compose-app
docker_compose_project_dir: "/opt/{{ docker_compose_project_name }}"
docker_compose_file_path: "{{ docker_compose_project_dir }}/compose.yaml"
docker_compose_env_path: "{{ docker_compose_project_dir }}/.env"
docker_compose_systemd_unit_name: "{{ docker_compose_project_name }}.service"
docker_compose_systemd_unit_path: "/etc/systemd/system/{{ docker_compose_systemd_unit_name }}"
docker_compose_example_image: nginx:stable-alpine
docker_compose_example_port: 8080
