---
- name: Update CA certificates
  become: true
  ansible.builtin.command:
    cmd: update-ca-certificates
  changed_when: true

- name: Restart Docker if present
  become: true
  ansible.builtin.systemd:
    name: docker
    state: restarted
  failed_when: false
