---
portainer_primary_user: root
portainer_project_name: portainer
portainer_project_dir: "/opt/portainer"
portainer_compose_file: "{{ portainer_project_dir }}/compose.yaml"

portainer_image: portainer/portainer-ce:latest
portainer_container_name: portainer
portainer_restart_policy: unless-stopped

portainer_data_dir: "{{ portainer_project_dir }}/data"

# Traefik integration
portainer_network_name: traefik_proxy
portainer_traefik_hostname: "portainer.taylor.lan"
portainer_traefik_entrypoint: web

portainer_systemd_unit: portainer.service
portainer_systemd_unit_path: "/etc/systemd/system/{{ portainer_systemd_unit }}"
