- name: Install dns utils
  ansible.builtin.apt:
    name:
      - dnsutils
      - dnsmasq
    state: present

- name: Install dns utils
  ansible.builtin.file:
    src: hosts
    dest: /etc/hosts
    state: present
