- name: Install dns utils
  become: true
  ansible.builtin.apt:
    name:
      - dnsutils
      - dnsmasq
    state: present

- name: Install DNS File
  become: true
  ansible.builtin.copy:
    src: files/hosts
    dest: /etc/hosts