- name: Install dns utils
  become: true
  ansible.builtin.apt:
    name:
      - dnsutils
      - dnsmasq
    state: present

- name: Clean up APT
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true

- name: Install dns utils
  become: true
  ansible.builtin.file:
    src: hosts
    dest: /etc/hosts
    state: present
