---
grafana_primary_user: root
grafana_project_name: grafana
grafana_project_dir: "/opt/grafana"
grafana_compose_file: "{{ grafana_project_dir }}/compose.yaml"

grafana_image: grafana/grafana:latest
grafana_container_name: grafana
grafana_restart_policy: unless-stopped

grafana_data_dir: "{{ grafana_project_dir }}/data"
grafana_provisioning_dir: "{{ grafana_project_dir }}/provisioning"
grafana_datasources_dir: "{{ grafana_provisioning_dir }}/datasources"
grafana_datasource_path: "{{ grafana_datasources_dir }}/datasource.yaml"
grafana_container_uid: "472"
grafana_container_gid: "472"

grafana_admin_username: "admin"
grafana_admin_password: "{{ vault_grafana_admin_password | default('change-me') }}"

grafana_prometheus_url: "http://prometheus:9090"

# LDAP auth integration (LLDAP)
grafana_auth_ldap_enabled: true
grafana_auth_ldap_allow_sign_up: true
grafana_ldap_config_path: "{{ grafana_project_dir }}/ldap.toml"
grafana_ldap_host: "lldap"
grafana_ldap_port: 3890
grafana_ldap_use_ssl: false
grafana_ldap_start_tls: false
grafana_ldap_ssl_skip_verify: false
grafana_ldap_bind_dn: "cn=admin,ou=people,dc=taylor,dc=lan"
grafana_ldap_bind_password: "{{ vault_lldap_ldap_user_pass | default('change-me') }}"
grafana_ldap_search_filter: "(uid=%s)"
grafana_ldap_search_base_dns:
  - "ou=people,dc=taylor,dc=lan"

# Traefik integration
grafana_network_name: traefik_proxy
grafana_traefik_hostname: "grafana.taylor.lan"
grafana_traefik_entrypoint: web

grafana_systemd_unit: grafana.service
grafana_systemd_unit_path: "/etc/systemd/system/{{ grafana_systemd_unit }}"
