- name: Install common packages
  become: true
  ansible.builtin.apt:
    name:
      - nano
      - git
    state: present
    lock_timeout: 600

- name: Clean up APT
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    lock_timeout: 600
