- name: Install common packages
  become: true
  apt:
    name:
      - nano
      - git
      - python3
    state: present

- name: Clean up APT
  become: true
  apt:
    autoclean: true
    autoremove: true
